=== yrtimiD/osmpoi-android/assets/entity_formatters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="formatters" type="formattersType" />

    <xsd:complexType name="formattersType">
    	<xsd:sequence>
    		<xsd:element name="formatter" type="formatterType" maxOccurs="unbounded" minOccurs="0"/>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="formatterType">
    	<xsd:attribute name="match" type="xsd:string" use="required" />
    	<xsd:attribute name="select_pattern" type="xsd:string" use="required" />
    </xsd:complexType>
    
</xsd:schema>

=== yrtimiD/osmpoi-android/OsmPoi-Android/assets/entity_formatters.xml
<?xml version="1.0" encoding="UTF-8"?>
<formatters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="entity_formatters.xsd">
	<formatter match="amenity=atm" select_pattern="ATM {operator}" ></formatter>
	<formatter match="shop=*" select_pattern="{name} ({shop})" ></formatter>
	<formatter match="operator*=* &amp; name*=*" select_pattern="{name} ({operator})"/>
	<formatter match="amenity=* &amp; name*=*" select_pattern="{name} ({amenity})"/>
	<formatter match="leisure=* &amp; name*=*" select_pattern="{name} ({leisure})"/>
	<formatter match="name*=*" select_pattern="{name}"/>
	<formatter match="amenity=*" select_pattern="{amenity}"/>
	<formatter match="highway=*" select_pattern="{highway}"/>
	<formatter match="building=* &amp; addr:street=* &amp; addr:housenumber=*" select_pattern="{addr:street} {addr:housenumber}" />
	<formatter match="building=* &amp; addr:street=* &amp; addr:housename=*" select_pattern="{addr:street} {addr:housename}" />
	<formatter match="building=* &amp; addr:housenumber=*" select_pattern="{addr:housenumber}" />
	<formatter match="building=* &amp; addr:housename=*" select_pattern="{addr:housename}" />
	<formatter match="building=* &amp; !(building=yes)" select_pattern="{building}" />
	<formatter match="building=yes" select_pattern="building" />
	<formatter match="addr:street=* &amp; addr:housenumber=*" select_pattern="{addr:street} {addr:housenumber}" />
	<formatter match="addr:street=* &amp; addr:housename=*" select_pattern="{addr:street} {addr:housename}" />
	<formatter match="addr:housenumber=*" select_pattern="{addr:housenumber}" />
	<formatter match="addr:housename=*" select_pattern="{addr:housename}" />
</formatters>
